### ISSUE TITLE
OSError: cannot identify image file 'images\\checkpoint'

### ISSUE THREAD

**Issue by Kadantte** [deeppomf/DeepMindBreak#11]
python to_npy.py
Traceback (most recent call last):
  File "to_npy.py", line 18, in <module>
    temp = Image.open(path)
  File "C:\Users\minat\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 2622, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'images\\checkpoint'

**Comment by Kadantte** [comment]
My bad i Fix it xD
